### PR TITLE
Add `require`s to README

### PR DESCRIPTION
**Pull request by mparramont**
I needed to add them to make `workflow` work for me, maybe it's the same for everybody else? 😄

### CODE REVIEW

**Comment by ridiculous** [comment]
I had to do this to. I think the more conventional way is to define the file `workflow-activerecord.rb`, which bundler will try to require automatically.

**Comment by geekq** [comment]
Thanks for your README expansion @mparramont !

The better way would be to reorganize the source code as described in https://github.com/geekq/workflow-activerecord/issues/3#issuecomment-484513764.

File `workflow-activerecord.rb` is unfortunately not enough @ridiculous.

**Comment by ridiculous** [comment]
sure that would work too. FYI can't use this gem on ruby 2.6, get an error just trying to mount `WorkflowActiverecord` it throws an undefined method `workflow` for class.

**Comment by geekq** [comment]
@ridiculous regarding Ruby 2.6, can you please create a separate issue including steps to reproduce and exact Ruby, Rails versions?

BTW, there is a build for Ruby 2.6 + Rails 6.0 at https://travis-ci.org/geekq/workflow-activerecord and at least the unit tests work there.

**Comment by ridiculous** [comment]
Thanks @geekq, I created the issue here https://github.com/geekq/workflow-activerecord/issues/7

**Comment by stefanahman** [comment]
@ridiculous Please add a pull request with your changes

**Comment by stefanahman** [comment]
> @ridiculous Please add a pull request with your changes

Will this resolve the require issue? https://github.com/ridiculous/workflow-activerecord/commit/7395c9087731889f55203bd8ad2d5f391f6abfc2

**Comment by geekq** [comment]
> Will this resolve the require issue? [ridiculous@7395c90](https://github.com/ridiculous/workflow-activerecord/commit/7395c9087731889f55203bd8ad2d5f391f6abfc2)

Tested - works! Thanks @stefanahman for pointing this out! Thanks @ridiculous for the solution!
This solution is easier than refactoring to nested modules like Workflow::ActiveRecord

Next step would be to consolidate the whole implementation in the single lib/workflow-activerecord.rb file and mark `workflow_activerecord` usage (the thing with the underscore) deprecated.

**Comment by geekq** [comment]
Also released workflow-activerecord 4.1.6 gem to rubygems.org

**Pull request closed without merging**
